version: '3.1'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: news_bot
      PG_DATA: /var/lib/postgresql/data/
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data/

  bot:
    build:
      context: .
    restart: on-failure
    
    environment:
      NB_DATABASE_DSN: ${NB_DATABASE_DSN:-postgres://postgres:postgres@db:5432/news_bot?sslmode=disable}
      NB_TELEGRAM_BOT_TOKEN: ${NB_TELEGRAM_BOT_TOKEN}
      NB_TELEGRAM_CHANNEL_ID: ${NB_TELEGRAM_CHANNEL_ID}
      NB_FETCH_INTERVAL: ${NB_FETCH_INTERVAL}
      NB_NOTIFICATION_INTERVAL: ${NB_NOTIFICATION_INTERVAL}
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db: 
